name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    #- name: cstrace build prepare
    #  run: cmake -B ${{github.workspace}}/build -DCMAKE_INSTALL_PREFIX=${{github.workspace}}
      
    #- name: cstrace build
    #  run: cmake --build ${{github.workspace}}/build

    - name: cxbuild build
      uses: JackMcKew/pyinstaller-action-linux@0.1.4
      with: 
        spec: build.spec
    
    - run: chmod +x ${{github.workspace}}/dist/linux/cxbuild
    #- run: ${{github.workspace}}/dist/linux/cxbuild |> echo
    - run: cp ${{github.workspace}}/dist/linux/cxbuild ${{github.workspace}}/bin/cxbuild
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{github.workspace}}/bin/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
        release_name: cxbuild-release-${{ github.ref }}
    
