name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-18.04

    steps:
    - name: shorten SHA
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      
    - uses: actions/checkout@v2
    - run: mkdir ${{github.workspace}}/bin
    - name: cstrace build prepare
      run: cmake -B ${{github.workspace}}/build -DCMAKE_INSTALL_PREFIX=${{github.workspace}}
      
    - name: cstrace build
      run: cmake --build ${{github.workspace}}/build

    - name: cxbuild build
      uses: JackMcKew/pyinstaller-action-linux@0.1.4
      with: 
        spec: build.spec
    
    - run: chmod +x ${{github.workspace}}/dist/linux/cxbuild
    - run: cp ${{github.workspace}}/dist/linux/cxbuild ${{github.workspace}}/bin/cxbuild
    
    - name: Zip
      uses: papeloto/action-zip@v1
      with:
        files: bin/cstrace bin/cxbuild
        dest: Release-cxbuild-${{ runner.os }}-${{ steps.vars.outputs.sha_short }}.zip
          
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release cxbuild-${{ steps.vars.outputs.sha_short }} for ${{ runner.os }} 
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Release-cxbuild-${{ runner.os }}-${{ steps.vars.outputs.sha_short }}.zip
        asset_name: Release-cxbuild-${{ runner.os }}-${{ steps.vars.outputs.sha_short }}.zip
        asset_content_type: application/zip
        
