name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: cstrace build prepare
      run: cmake -B ${{github.workspace}}/build -DCMAKE_INSTALL_PREFIX=${{github.workspace}}
      
    - name: cstrace build
      run: cmake --build ${{github.workspace}}/build

    - name: cxbuild build
      # Build your program with the given configuration
      uses: JackMcKew/pyinstaller-action-linux@0.1.4
      with: 
        spec: build.spec
    
    - run: chmod +x ${{github.workspace}}/dist/linux/cxbuild
    - run: ${{github.workspace}}/dist/linux/cxbuild
    - run: cp ${{github.workspace}}/dist/linux/cxbuild ${{github.workspace}}/bin/cxbuild
    
    
    - name: packaging
      uses: actions/upload-artifact@v2
      with:
        name: Release
        path: ${{github.workspace}}/bin/

      
